# Generated by Django 2.2.4 on 2021-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stocks', models.TextField()),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('r_o_a', models.DecimalField(decimal_places=2, max_digits=15)),
                ('p_or_e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lowest_price_in_52w', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=15)),
                ('masses_in_circulation', models.IntegerField()),
                ('company_value', models.IntegerField()),
                ('e_s_p', models.DecimalField(decimal_places=2, max_digits=15)),
                ('r_o_e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('p_or_b', models.DecimalField(decimal_places=2, max_digits=15)),
                ('magic_formula', models.DecimalField(decimal_places=1, max_digits=15)),
                ('is_big_enough', models.NullBooleanField()),
                ('is_lowest', models.NullBooleanField()),
                ('date_update', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('capital', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
