# Generated by Django 2.2.4 on 2021-04-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='efficiency_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='p_e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='r_o_a',
            field=models.IntegerField(default=0),
        ),
    ]
