# Generated by Django 2.2.4 on 2021-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210407_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
